// Given a String , we have to find out all its subsequences of it.A string is a subsequence of a given String , that is generated by deleting some character of a given string without changing its order.

#include<bits/stdc++.h>
using namespace std;
void findSubsequence(string &str, int i, string result, vector<string> &li ){
    // base case
    if(i==str.length()){
        li.push_back(result);
        return ;
    }
    //   include current character
     findSubsequence(str,i+1,result+str[i],li);

    //  Exclude current character
     findSubsequence(str,i+1,result,li);
}
int main(){
     vector<string>res;
     string str="abc";
     findSubsequence(str,0,"",res);
     for(int i=0;i<res.size();i++){
        cout<<res[i]<<" ";
     }
    return 0;
}
